#!/usr/bin/env bash

ROOT_DIR="$(pwd)/"
PHPCS_BIN=vendor/bin/dockworker

if [ ! -f $PHPCS_BIN ];
then
  echo "DockWorker was not found in this project's bin directory. Please run composer install. "
  exit 1
fi

echo "Validating commit message..."
exec < /dev/tty
${ROOT_DIR}/vendor/bin/dockworker validate:git:commit-msg "$1" || exit 1;

# Return the status of the last run command.
exit $?
