#!/usr/bin/env bash
ROOT_DIR="$(pwd)/"
LIST=$( git diff --name-only --cached --diff-filter=ACM )

if [[ "$LIST" == "" ]];
then
  echo "No added or modified files in this commit set. Skipping Linting!"
  exit 0
fi

DOCKWORKER_BIN="${ROOT_DIR}/vendor/bin/dockworker"
if [ ! -f $DOCKWORKER_BIN ];
then
  echo "Dockworker was not found in this project's bin directory. Please run composer install."
  exit 1
fi

echo "Linting YML files..."
${ROOT_DIR}/vendor/bin/dockworker validate:yaml --staged
SNIFF_STATUS=$?
if [ $SNIFF_STATUS -ne 0 ]; then
  exec < /dev/tty
  read -p "The YAML file lint reported one or more errors. Would you still like to continue anyhow? " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborting due to failed YAML lint."
    exit $SNIFF_STATUS
  fi
fi

if [[ $LIST == *"composer."* ]];
then
  printf "\nValidating /composer.json..."
  composer validate || exit 1;
fi
echo "/composer.json Ok!"

# Return the status of the last run command.
exit $?
