name: Build Image and Push, then Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      branch-env-map:
        description: 'A mapping of branches-to-k8s-namespaces. JSON dictionary format.'
        required: true
        type: string
      build-themes:
        description: 'Whether or not to build application themes using dockworker before building the image.'
        required: false
        type: boolean
        default: false
      deploy-branches:
        description: 'A list of branches that should be deployed to kubernetes cluster. JSON list format.'
        required: true
        type: string
      image-name:
        description: 'The full, repository namespaced image name to build (without the tag).'
        required: true
        type: string
      k8s-deployment-name:
        description: 'The name of the kubernetes deployment to update.'
        required: true
        type: string
      push-branches:
        description: 'A list of branches that should be pushed to the container registry. JSON list format.'
        required: true
        type: string
      platforms:
        description: "A comma-separated list of platforms."
        required: false
        type: string
        default: linux/amd64,linux/arm64/v8
    secrets:
      KUBE_CONFIG:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      GH_CONTAINER_REGISTRY_USER:
        required: true
      GH_CONTAINER_REGISTRY_TOKEN:
        required: true

jobs:
  notify-start:
    name: Notify of Start
    if: always()
    uses: unb-libraries/dockworker/.github/workflows/notify-start.yaml@6.x
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-push-images:
    uses: unb-libraries/dockworker/.github/workflows/build-push.yaml@6.x
    with:
      build-themes: ${{ inputs.build-themes }}
      image-name: ${{ inputs.image-name }}
      push-branches: ${{ inputs.push-branches }}
      platforms: ${{ inputs.platforms }}
    secrets:
      GH_CONTAINER_REGISTRY_USER: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
      GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}

  deploy-image-to-k8s:
    uses: unb-libraries/dockworker/.github/workflows/deploy.yaml@6.x
    needs: [ build-push-images ]
    with:
      branch-env-map: ${{ inputs.branch-env-map }}
      deploy-branches: ${{ inputs.deploy-branches }}
      k8s-deployment-name: ${{ inputs.k8s-deployment-name }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  test-logs:
    uses: unb-libraries/dockworker/.github/workflows/test-logs.yaml@6.x
    needs: [ deploy-image-to-k8s ]

  notify-conclusion:
    name: Notify of Conclusion
    uses: unb-libraries/dockworker/.github/workflows/notify-conclusion.yaml@6.x
    needs: [ test-logs ]
    if: always()
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
