name: Build Image and Push To Registry

on:
  workflow_call:
    inputs:
      image-name:
        description: 'The full, repository namespaced image name to build (without the tag).'
        required: true
        type: string
      push-branches:
        description: 'A list of branches that should be pushed to the container registry. JSON list format.'
        required: true
        type: string
    secrets:
      GH_CONTAINER_REGISTRY_USER:
        description: 'The user to use to login to the GitHub Container Registry.'
        required: true
      GH_CONTAINER_REGISTRY_TOKEN:
        description: 'The token to use to login to the GitHub Container Registry.'
        required: true

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v3
      -
        name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDHHMMSS
      -
        name: Set Hashed Tag
        env:
          TIMESTAMP: ${{ steps.current-time.outputs.formattedTime }}
        run: echo "BUILD_IMAGE_TAG=$CI_SHA_SHORT-$TIMESTAMP" >> $GITHUB_ENV
      -
        name: Set Hashed Image Full Name
        env:
          TIMESTAMP: ${{ steps.current-time.outputs.formattedTime }}
          IMAGE_NAME: ${{ inputs.push-branches }}
        run: echo "BUILD_IMAGE_FULL_NAME=$IMAGE_NAME:$CI_SHA_SHORT-$TIMESTAMP" >> $GITHUB_ENV
      -
        name: Set Branched Image Full Name
        env:
          TIMESTAMP: ${{ steps.current-time.outputs.formattedTime }}
          IMAGE_NAME: ${{ inputs.push-branches }}
        run: echo "BUILD_IMAGE_BRANCH_NAME=$IMAGE_NAME:$CI_REF_NAME" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
      - name: Determine Push Tags
        uses: haya14busa/action-cond@v1
        id: fetch-tags
        with:
          cond: ${{ contains(fromJSON(inputs.push-branches), github.ref_name) }}
          if_true: "${{ env.BUILD_IMAGE_FULL_NAME }},${{ env.BUILD_IMAGE_BRANCH_NAME }}"
          if_false: ${{ env.BUILD_IMAGE_FULL_NAME }}
      -
        env:
          TIMESTAMP: ${{ steps.current-time.outputs.time }}
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64/v8
          context: .
          file: ./Dockerfile
          tags: ${{ steps.fetch-tags.outputs.value }}
          build-args: |
            BUILD_DATE=$TIMESTAMP
            VCS_REF=${{ env.CI_REF_NAME }}
            VERSION=${{ env.BUILD_IMAGE_TAG }}
