name: Dockworker OS Support Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  install_run_test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v3
      -
        name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
          tools: composer:v2
          extensions: curl,dom,gd,mbstring,posix,yaml,zip
      -
        name: Install dockworker
        run: composer install
        shell: bash
      -
        name: Test dockworker bootstrap
        run: vendor/bin/dockworker bootstrap
        shell: bash
