name: Trim unused registry images

on:
  workflow_call:
    inputs:
      image-name:
        description: 'The full, repository namespaced image name to trim (without the tag).'
        required: true
        type: string
      push-branches:
        description: 'A list of branches that are pushed to the container registry. JSON list format.'
        required: true
        type: string
      cleanup-old-images:
        description: 'Whether or not to cleanup legacy hash-tagged images from the container registry.'
        required: false
        type: boolean
        default: true
      cut-off:
        description: 'The cut-off date for images to be deleted. Images older than this date will be deleted. UTC format.'
        type: string
        required: false
        default: '4w'
      keep-n-most-recent:
        description: 'The minimum number of images to keep.'
        type: string
        required: false
        default: '5'
      protected-tags:
        description: 'A list of tags whose container images should be protected from deletion in cleanup. This is in addition to push-branches, which are always protected. CSV format. Wildcards via asterix are supported.'
        type: string
        required: false
        default: ''
    secrets:
      GH_CONTAINER_REGISTRY_USER:
        description: 'The user to use to login to the GitHub Container Registry.'
        required: true
      GH_CONTAINER_REGISTRY_TOKEN:
        required: true

jobs:
  trim-registry-images:
    if: ${{ inputs.cleanup-old-images == true && && github.event_name == 'push' && contains(fromJSON(inputs.push-branches), github.ref_name) }}
    name: Trim Registry
    runs-on: ubuntu-latest
    steps:
      -
        name: Convert Push Branch JSON to CSV
        env:
          PUSH_BRANCHES: ${{ inputs.push-branches }}
        run: echo "$PUSH_BRANCHES" | jq --raw-output '. | join(",")' | sed 's/^/PUSH_BRANCH_LIST=/' >> $GITHUB_ENV
      -
        name: Build full list of protected tags
        uses: haya14busa/action-cond@v1
        id: fetch-protected-tags
        with:
          cond: ${{ inputs.protected-tags != '' }}
          if_true: "${{ inputs.protected-tags }},${{ env.PUSH_BRANCH_LIST }}"
          if_false: ${{ env.PUSH_BRANCH_LIST }}
      -
        name: Set Protected Tags List
        env:
          PROTECTED_TAGS: ${{ steps.fetch-protected-tags.outputs.value }}
        run: echo "PROTECTED_TAG_LIST=$PROTECTED_TAGS" | sed 's/,$//g' >> $GITHUB_ENV
      - 
        name: Install Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
        shell: bash
      -
        name: Download Hash Listing Script
        run: |
          curl -L https://raw.githubusercontent.com/unb-libraries/dockworker/6.x/data/scripts/determineHashesToSkip.sh -o determineHashesToSkip.sh
          chmod +x determineHashesToSkip.sh
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
      -
        name: Set Hashes to Skip
        id: set-hashes-to-skip
        run: ./determineHashesToSkip.sh "${{ inputs.image-name }}" "${{ env.PROTECTED_TAG_LIST }}" >> $GITHUB_OUTPUT
        env:
          GH_CONTAINER_REGISTRY_USER: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
          GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
      - name: Extract the repository owneronly from image-name
        id: extract-repo-owner
        run: echo "REPOSITORY_OWNER_COMPONENT=$(echo ${{ inputs.image-name }} | cut -d '/' -f 2)" >> $GITHUB_ENV
      - name: Extract the repository name only from image-name
        id: extract-repo-name
        run: echo "REPOSITORY_NAME_COMPONENT=$(echo ${{ inputs.image-name }} | cut -d '/' -f 3)" >> $GITHUB_ENV
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ env.REPOSITORY_OWNER_COMPONENT }}
          cut-off: ${{ inputs.cut-off }}
          image-names: ${{ env.REPOSITORY_NAME_COMPONENT }}
          keep-n-most-recent: ${{ inputs.keep-n-most-recent }}
          skip-shas: ${{ steps.set-hashes-to-skip.outputs.hashes-to-skip }}
          token: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
          rust-log: container_retention_policy=DEBUG
