name: Update Application and Dependencies

on:
  workflow_call:
    inputs:
      add-paths:
        description: 'A list of relative paths to add in the PR. Paths should follow git pathspec syntax'
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        description: 'The token to use for creating the pull request'
        required: true

jobs:
  update-application:
    name: Update Application and Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: unb-libraries/install-dockworker-composite-action@v2
      - name: Remove Dockworker-Installed git Hooks
        run: rm -f .git/hooks/commit-msg .git/hooks/pre-commit
      - name: Update Application and Dependencies
        shell: 'script -q -e -c "bash {0}"'
        run: vendor/bin/dockworker update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Update Application and Dependencies
          committer: UNB Libraries CodeBot <libsystems@unb.ca>
          author: UNB Libraries CodeBot <libsystems@unb.ca>
          signoff: false
          branch: application-updates
          add-paths: ${{ inputs.add-paths }}
          delete-branch: true
          title: 'Application Updates'
          body: |
            Auto-generated by [dockworker][1]

            [1]: https://github.com/unb-libraries/dockworker/.github/workflows/update.yaml
          labels: |
            automated
            updates
          draft: false
